# DSC502: Coding — Week 4 Homework Notebook
## pandas — Working with Real Data
### RideAlong ride-hailing scenario

---

**RideAlong** is a fictional ride-hailing platform. This dataset contains 150 trips across 8 drivers and 5 cities, with fares, distances, durations, and customer ratings.

The scope is identical to the session — all pandas methods covered today plus dictionaries. More independent than the session: attempt each exercise before reaching for any help.

**Data file:** `../data/ridealong_trips.csv`

**Columns:** trip_id, customer_name, customer_city, driver_name, vehicle_type, driver_rating, trip_date, pickup_city, fare, distance_km, duration_mins, status, rating, review_text

---

### The AI rule

Still Phase 1. **No AI generation.** Debug-help only. Commentary cells required after every exercise.

---

## Exercise 1 — Load and explore

Load the RideAlong CSV. Run `.head()`, `.shape`, `.info()`, and `.describe()`.

In [2]:
import pandas as pd

df = pd.read_csv("../data/ridealong_trips.csv")
df.head()

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
0,TRP0001,Maya Taylor,Manchester,James Patel,Standard,3.8,2024-03-09,London,14.43,9.5,73,Completed,5.0,On time and friendly.
1,TRP0002,Noah Wilson,Bristol,Aisha Kofi,Standard,4.7,2024-07-10,Leeds,38.71,30.3,64,Completed,5.0,"Great driver, very smooth ride."
2,TRP0003,Quinn Jones,Leeds,Priya Sharma,Electric,4.1,2024-05-17,Bristol,3.88,1.3,73,Completed,4.0,Will use again.
3,TRP0004,Bob Brown,Manchester,Aisha Kofi,Standard,4.9,2024-03-23,Leeds,30.87,21.2,69,Completed,NaN,NaN
4,TRP0005,Alice Patel,Leeds,Leon Baptiste,Standard,3.6,2024-08-05,London,11.05,5.9,53,Completed,NaN,NaN

In [4]:
# shape
df.shape

(150, 14)

In [7]:
# info
df.info

<bound method DataFrame.info of      trip_id customer_name customer_city    driver_name vehicle_type  \
0    TRP0001   Maya Taylor    Manchester    James Patel     Standard
1    TRP0002   Noah Wilson       Bristol     Aisha Kofi     Standard
2    TRP0003   Quinn Jones         Leeds   Priya Sharma     Electric
3    TRP0004     Bob Brown    Manchester     Aisha Kofi     Standard
4    TRP0005   Alice Patel         Leeds  Leon Baptiste     Standard
..       ...           ...           ...            ...          ...
145  TRP0146   Liam Wilson         Leeds  Leon Baptiste     Standard
146  TRP0147    Liam Ahmed    Manchester     Marcus Obi    Executive
147  TRP0148    Jack Jones    Birmingham      Tom Walsh    Executive
148  TRP0149  Grace Taylor       Bristol     Marcus Obi    Executive
149  TRP0150   Alice Davis    Manchester      Tom Walsh    Executive

     driver_rating   trip_date pickup_city   fare  distance_km  duration_mins  \
0              3.8  2024-03-09      London  14.43          9.5             73
1              4.7  2024-07-10       Leeds  38.71         30.3             64
2              4.1  2024-05-17     Bristol   3.88          1.3             73
3              4.9  2024-03-23       Leeds  30.87         21.2             69
4              3.6  2024-08-05      London  11.05          5.9             53
..             ...         ...         ...    ...          ...            ...
145            3.7  2024-04-11       Leeds  28.76         22.5             60
146            3.7  2024-12-05     Bristol  19.34         12.0             35
147            3.6  2024-05-14  Manchester  44.57         35.0             84
148            4.8  2024-12-23      London  39.58         30.1             19
149            4.5  2024-10-07      London   8.38          2.8             45

        status  rating                      review_text
0    Completed     5.0            On time and friendly.
1    Completed     5.0  Great driver, very smooth ride.
2    Completed     4.0                  Will use again.
3    Completed     NaN                              NaN
4    Completed     NaN                              NaN
..         ...     ...                              ...
145  Completed     1.0                Long route taken.
146  Completed     NaN                              NaN
147  Completed     5.0               Excellent service.
148  Completed     NaN                              NaN
149  Cancelled     NaN                              NaN

[150 rows x 14 columns]>

In [2]:
# describe
df.describe()

       driver_rating        fare  distance_km  duration_mins     rating
count     150.000000  150.000000   150.000000     150.000000  99.000000
mean        4.185333   23.763867    16.969333      44.013333   3.636364
std         0.436026   11.639235     9.638847      24.821507   1.328299
min         3.500000    2.970000     1.000000       5.000000   1.000000
25%         3.800000   14.050000     8.850000      23.250000   3.000000
50%         4.150000   23.340000    16.700000      41.500000   4.000000
75%         4.575000   33.997500    26.175000      64.000000   5.000000
max         5.000000   45.800000    35.000000      90.000000   5.000000

In [9]:
# Most common vehicle type
df["vehicle_type"].value_counts()

vehicle_type
Standard     63
Executive    51
Electric     36
Name: count, dtype: int64

### Commentary — Exercise 1

1. How many trips are in the dataset?
2. Which columns have missing values?
3. What is the average fare and the range?
4. What is the most common vehicle type?
5. What does the dataset tell you about RideAlong before any filtering or grouping? What questions would an operations manager want to answer with this data?

*Your commentary here*

---
## Exercise 2 — Selecting and filtering

1. Select only `driver_name`, `fare`, `distance_km`, and `rating`
2. Filter to completed trips only
3. Filter to trips over 10km
4. Filter to London trips with a fare over £15
5. Filter to trips with a rating of 1 or 2 — how many poor experiences are there?

In [5]:
df[["driver_name", "fare","distance_km","rating", "status"]]

       driver_name   fare  distance_km  rating     status
0      James Patel  14.43          9.5     5.0  Completed
1       Aisha Kofi  38.71         30.3     5.0  Completed
2     Priya Sharma   3.88          1.3     4.0  Completed
3       Aisha Kofi  30.87         21.2     NaN  Completed
4    Leon Baptiste  11.05          5.9     NaN  Completed
..             ...    ...          ...     ...        ...
145  Leon Baptiste  28.76         22.5     1.0  Completed
146     Marcus Obi  19.34         12.0     NaN  Completed
147      Tom Walsh  44.57         35.0     5.0  Completed
148     Marcus Obi  39.58         30.1     NaN  Completed
149      Tom Walsh   8.38          2.8     NaN  Cancelled

[150 rows x 5 columns]

In [9]:
# 2
df[df["status"] == "Completed"]

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
0,TRP0001,Maya Taylor,Manchester,James Patel,Standard,3.8,2024-03-09,London,14.43,9.5,73,Completed,5.0,On time and friendly.
1,TRP0002,Noah Wilson,Bristol,Aisha Kofi,Standard,4.7,2024-07-10,Leeds,38.71,30.3,64,Completed,5.0,"Great driver, very smooth ride."
2,TRP0003,Quinn Jones,Leeds,Priya Sharma,Electric,4.1,2024-05-17,Bristol,3.88,1.3,73,Completed,4.0,Will use again.
3,TRP0004,Bob Brown,Manchester,Aisha Kofi,Standard,4.9,2024-03-23,Leeds,30.87,21.2,69,Completed,NaN,NaN
4,TRP0005,Alice Patel,Leeds,Leon Baptiste,Standard,3.6,2024-08-05,London,11.05,5.9,53,Completed,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,TRP0145,Kavya Smith,Leeds,Leon Baptiste,Standard,3.5,2024-07-10,London,35.62,26.9,38,Completed,4.0,Excellent service.
145,TRP0146,Liam Wilson,Leeds,Leon Baptiste,Standard,3.7,2024-04-11,Leeds,28.76,22.5,60,Completed,1.0,Long route taken.
146,TRP0147,Liam Ahmed,Manchester,Marcus Obi,Executive,3.7,2024-12-05,Bristol,19.34,12.0,35,Completed,NaN,NaN
147,TRP0148,Jack Jones,Birmingham,Tom Walsh,Executive,3.6,2024-05-14,Manchester,44.57,35.0,84,Completed,5.0,Excellent service.
148,TRP0149,Grace Taylor,Bristol,Marcus Obi,Executive,4.8,2024-12-23,London,39.58,30.1,19,Completed,NaN,NaN

In [ ]:
# 3

df[df["distance_km"] > 10]

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
1,TRP0002,Noah Wilson,Bristol,Aisha Kofi,Standard,4.7,2024-07-10,Leeds,38.71,30.3,64,Completed,5.0,"Great driver, very smooth ride."
3,TRP0004,Bob Brown,Manchester,Aisha Kofi,Standard,4.9,2024-03-23,Leeds,30.87,21.2,69,Completed,NaN,NaN
5,TRP0006,Maya Chen,London,Aisha Kofi,Standard,4.2,2024-10-06,Leeds,36.93,29.1,65,Completed,NaN,NaN
6,TRP0007,Tom Patel,Bristol,Leon Baptiste,Standard,3.7,2024-03-01,Manchester,18.78,11.1,57,Completed,1.0,Long route taken.
7,TRP0008,Priya Chen,Birmingham,Sarah Chen,Electric,4.8,2024-07-04,Manchester,32.42,24.1,6,Cancelled,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,TRP0145,Kavya Smith,Leeds,Leon Baptiste,Standard,3.5,2024-07-10,London,35.62,26.9,38,Completed,4.0,Excellent service.
145,TRP0146,Liam Wilson,Leeds,Leon Baptiste,Standard,3.7,2024-04-11,Leeds,28.76,22.5,60,Completed,1.0,Long route taken.
146,TRP0147,Liam Ahmed,Manchester,Marcus Obi,Executive,3.7,2024-12-05,Bristol,19.34,12.0,35,Completed,NaN,NaN
147,TRP0148,Jack Jones,Birmingham,Tom Walsh,Executive,3.6,2024-05-14,Manchester,44.57,35.0,84,Completed,5.0,Excellent service.
148,TRP0149,Grace Taylor,Bristol,Marcus Obi,Executive,4.8,2024-12-23,London,39.58,30.1,19,Completed,NaN,NaN

In [12]:
# 4
df[(df["customer_city"] == "London") & (df["fare"] < 15)]

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
45,TRP0046,Alice Taylor,London,Leon Baptiste,Standard,4.2,2024-02-12,London,14.35,7.6,35,Completed,4.0,Excellent service.
79,TRP0080,Alice Jones,London,James Patel,Standard,3.5,2024-02-14,London,6.02,3.5,39,Completed,4.0,Will use again.
100,TRP0101,Sophie Davis,London,Priya Sharma,Electric,4.3,2024-05-28,Leeds,7.37,2.2,10,Completed,4.0,Will use again.
120,TRP0121,Maya Jones,London,Sarah Chen,Electric,4.2,2024-04-14,Bristol,13.01,7.5,23,Cancelled,NaN,NaN
127,TRP0128,Bob Jones,London,Leon Baptiste,Standard,3.8,2024-07-23,Bristol,6.21,3.2,33,Completed,4.0,"Great driver, very smooth ride."
131,TRP0132,Tom Wilson,London,Marcus Obi,Executive,3.7,2024-06-03,Birmingham,11.28,6.9,17,Completed,5.0,Excellent service.
141,TRP0142,Isla Davis,London,James Patel,Standard,3.6,2024-12-08,Bristol,11.27,5.8,83,Completed,3.0,OK trip.

In [18]:
# 5
df[df["rating"] <= 2].count()

trip_id          20
customer_name    20
customer_city    20
driver_name      20
vehicle_type     20
driver_rating    20
trip_date        20
pickup_city      20
fare             20
distance_km      20
duration_mins    20
status           20
rating           20
review_text      20
dtype: int64

**Stretch:** Filter to Electric vehicle trips with a rating of 5. What do you notice?

In [21]:
# Stretch
df[(df["vehicle_type"] == "Electric") & (df["rating"] == 5)]

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
10,TRP0011,Olivia Taylor,Birmingham,Sarah Chen,Electric,4.3,2024-12-16,Birmingham,36.99,27.8,37,Completed,5.0,On time and friendly.
31,TRP0032,Carol Chen,Birmingham,Priya Sharma,Electric,4.7,2024-06-20,Leeds,13.55,7.4,8,Completed,5.0,On time and friendly.
44,TRP0045,Emma Davis,Manchester,Priya Sharma,Electric,4.4,2024-02-06,Manchester,28.51,19.9,78,Completed,5.0,"Great driver, very smooth ride."
60,TRP0061,Isla Brown,Leeds,Priya Sharma,Electric,4.1,2024-05-15,Birmingham,34.64,27.6,75,Completed,5.0,Excellent service.
71,TRP0072,David Smith,Leeds,Priya Sharma,Electric,4.5,2024-12-26,London,11.22,6.9,80,Completed,5.0,Excellent service.
84,TRP0085,Liam Ahmed,Manchester,Sarah Chen,Electric,4.8,2024-02-04,London,10.60,6.8,72,Completed,5.0,Excellent service.
123,TRP0124,Alice Ahmed,Bristol,Sarah Chen,Electric,4.7,2024-03-12,Manchester,38.39,29.3,49,Completed,5.0,Will use again.
137,TRP0138,Liam Chen,Leeds,Priya Sharma,Electric,4.3,2024-05-01,Manchester,43.13,31.9,22,Completed,5.0,Excellent service.
140,TRP0141,David Jones,Manchester,Priya Sharma,Electric,4.0,2024-08-16,Leeds,19.54,12.6,58,Completed,5.0,"Great driver, very smooth ride."

### Commentary — Exercise 2

1. What is the difference between selecting columns and filtering rows?
2. Which filter produced the most surprising result for you, and why?

*Your commentary here*

---
## Exercise 3 — Sorting and groupby

1. Sort by `fare`, descending — what are the top 5 most expensive trips?
2. Sort by `distance_km`, ascending — what are the shortest trips?
3. Average fare by city — which city has the highest average fare?
4. Average rating by driver — who is the highest rated driver?
5. Count of trips by vehicle type
6. Average duration by city, sorted highest to lowest

In [3]:
# 1
df.sort_values(by="fare", ascending=False).head(5)

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
38,TRP0039,Jack Ahmed,Leeds,Leon Baptiste,Standard,4.7,2024-06-13,Bristol,45.80,34.9,73,Completed,5.0,On time and friendly.
90,TRP0091,Noah Williams,Bristol,Leon Baptiste,Standard,4.7,2024-09-23,Leeds,45.71,34.8,63,Cancelled,NaN,NaN
77,TRP0078,Hassan Chen,Leeds,Mei Zhang,Executive,3.9,2024-04-10,Leeds,44.65,33.0,41,Cancelled,NaN,NaN
147,TRP0148,Jack Jones,Birmingham,Tom Walsh,Executive,3.6,2024-05-14,Manchester,44.57,35.0,84,Completed,5.0,Excellent service.
137,TRP0138,Liam Chen,Leeds,Priya Sharma,Electric,4.3,2024-05-01,Manchester,43.13,31.9,22,Completed,5.0,Excellent service.

In [4]:
# 2
df.sort_values("distance_km", ascending=True)

,trip_id,customer_name,customer_city,driver_name,vehicle_type,driver_rating,trip_date,pickup_city,fare,distance_km,duration_mins,status,rating,review_text
125,TRP0126,Olivia Davis,Leeds,Sarah Chen,Electric,3.5,2024-06-07,London,2.97,1.0,5,Completed,4.0,Excellent service.
2,TRP0003,Quinn Jones,Leeds,Priya Sharma,Electric,4.1,2024-05-17,Bristol,3.88,1.3,73,Completed,4.0,Will use again.
32,TRP0033,Bob Williams,Manchester,Tom Walsh,Executive,4.9,2024-12-09,Birmingham,5.18,1.3,30,Completed,NaN,NaN
46,TRP0047,Jack Patel,Bristol,Aisha Kofi,Standard,3.6,2024-02-27,Birmingham,7.13,1.9,43,Completed,3.0,Average.
100,TRP0101,Sophie Davis,London,Priya Sharma,Electric,4.3,2024-05-28,Leeds,7.37,2.2,10,Completed,4.0,Will use again.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,TRP0140,Grace Davis,Leeds,James Patel,Standard,3.7,2024-10-01,Leeds,41.38,33.0,53,Completed,5.0,Will use again.
77,TRP0078,Hassan Chen,Leeds,Mei Zhang,Executive,3.9,2024-04-10,Leeds,44.65,33.0,41,Cancelled,NaN,NaN
90,TRP0091,Noah Williams,Bristol,Leon Baptiste,Standard,4.7,2024-09-23,Leeds,45.71,34.8,63,Cancelled,NaN,NaN
38,TRP0039,Jack Ahmed,Leeds,Leon Baptiste,Standard,4.7,2024-06-13,Bristol,45.80,34.9,73,Completed,5.0,On time and friendly.
147,TRP0148,Jack Jones,Birmingham,Tom Walsh,Executive,3.6,2024-05-14,Manchester,44.57,35.0,84,Completed,5.0,Excellent service.

In [5]:
# 3
df.groupby("pickup_city")["fare"].mean().sort_values(ascending=False).round(2)

pickup_city
Leeds         28.38
Manchester    25.18
Bristol       23.95
Birmingham    21.46
London        20.21
Name: fare, dtype: float64

In [6]:
# 4
df.groupby("driver_name")["rating"].agg(["mean", "count"]).sort_values("mean", ascending=False)

                   mean  count
driver_name
Sarah Chen     4.166667      6
Aisha Kofi     3.909091     11
Priya Sharma   3.823529     17
James Patel    3.692308     13
Leon Baptiste  3.647059     17
Tom Walsh      3.555556      9
Mei Zhang      3.444444      9
Marcus Obi     3.176471     17

In [7]:
# 5
df["vehicle_type"].value_counts()

vehicle_type
Standard     63
Executive    51
Electric     36
Name: count, dtype: int64

In [8]:
# 6
df.groupby("pickup_city")["duration_mins"].mean().sort_values(ascending=False).round(1)

pickup_city
Birmingham    52.3
London        47.1
Bristol       46.8
Leeds         39.2
Manchester    34.7
Name: duration_mins, dtype: float64

**Stretch:** Filter to completed trips only, then group by driver and calculate average rating from the trip `rating` column. How does this compare to the `driver_rating` column (which is a fixed field, not calculated from individual trip ratings)?

In [ ]:
# Stretch

### Commentary — Exercise 3

1. What did groupby tell you about the RideAlong drivers that you couldn't see from the raw data?
2. What business decisions could a RideAlong operations manager make based on these results?
3. What did you find hardest in this exercise?

*Your commentary here*

---
## Exercise 4 — Dictionary and DataFrame creation

1. Create a dictionary summarising 4 RideAlong drivers — name, vehicle type, and a made-up average rating. Print each entry using a for loop and `.items()`.
2. Create a small DataFrame from this dictionary using `pd.DataFrame()`.
3. Add a fifth driver by creating a new entry in the dictionary, then recreate the DataFrame.

In [9]:
# 1 — dictionary and loop
drivers = {
    "Leon Baptiste": {"vehicle_type": "Standard", "avg_rating": 4.7},
    "Mei Zhang": {"vehicle_type": "Executive", "avg_rating": 3.9},
    "Priya Sharma": {"vehicle_type": "Electric", "avg_rating": 4.3},
    "Tom Walsh": {"vehicle_type": "Executive", "avg_rating": 4.5},
}

for name, info in drivers.items():
    print(f"{name}: {info['vehicle_type']}, rating {info['avg_rating']}")

Leon Baptiste: Standard, rating 4.7
Mei Zhang: Executive, rating 3.9
Priya Sharma: Electric, rating 4.3
Tom Walsh: Executive, rating 4.5

In [10]:
# 2 — create DataFrame
df_drivers = pd.DataFrame.from_dict(drivers, orient="index")
df_drivers

              vehicle_type  avg_rating
Leon Baptiste     Standard         4.7
Mei Zhang        Executive         3.9
Priya Sharma      Electric         4.3
Tom Walsh        Executive         4.5

In [11]:
# 3 — add fifth driver, recreate
drivers["Aisha Kofi"] = {"vehicle_type": "Standard", "avg_rating": 3.6}
df_drivers = pd.DataFrame.from_dict(drivers, orient="index")
df_drivers

              vehicle_type  avg_rating
Leon Baptiste     Standard         4.7
Mei Zhang        Executive         3.9
Priya Sharma      Electric         4.3
Tom Walsh        Executive         4.5
Aisha Kofi        Standard         3.6

**Stretch:** Use `.dropna(subset=["rating"])` on the full RideAlong DataFrame. How many rows remain? Run your groupby from Exercise 3 again on this cleaned version — do any results change noticeably?

In [ ]:
# Stretch — dropna and rerun groupby

### Commentary — Exercise 4

1. What is a dictionary and how does it relate to a DataFrame?
2. What did dropping missing values change in your analysis — or didn't it? Why might that matter?

*Your commentary here*

---
## Final reflection

1. What is the most useful pandas method you learned this week, and why?
2. Where did you get genuinely stuck, and how did you get unstuck?
3. Did you use AI at any point? If so, what did you ask, and what did it tell you?
4. What question about the QuickBite or RideAlong data do you wish you could answer — and what would you need to learn to do it?

*Your reflection here*

---

```bash
git add . && git commit -m "week 4 homework" && git push
```

No Blackboard Journal action needed this week.