# DSC502: Coding — Week 4 Session Notebook
## pandas — Working with Real Data
### QuickBite food delivery scenario

---

**Weeks 1–3** we worked with data we typed ourselves: a handful of variables, a short list, a function on made-up numbers. This week that changes.

We're loading **150 QuickBite orders across 13 columns** — the kind of flat file that lands in your inbox as a database export or a client spreadsheet. We're going to explore it, filter it, sort it, and summarise it. By the end of session 2 you'll have answered questions about this dataset that you couldn't answer just by looking at it.

**Four questions connection:** *What data does your app actually need?* — pandas is how you find out. Every filter and groupby you run this week is answering that question on real data.

---

### The AI rule — still in force

Still Phase 1. **Copilot autocomplete is off.** Debug-help only. Next week that changes — and the pandas literacy you build today is exactly what lets you evaluate AI-generated data code.

---

### Before you start

- Open this notebook in your Codespace (`week04/` folder)
- The data file is at `../data/quickbite_orders.csv` — already in your repo
- Run cells in order with **Shift+Enter**
- Week 4 Course Companion is on Blackboard for the 'why' behind each method

---

## Part 1 — Loading and first look

### Import and load

Two lines. That's all it takes to go from a file on disk to a table in memory.

In [7]:
import pandas as pd

df = pd.read_csv("../data/quickbite_orders.csv")
df

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
0,ORD0001,David Smith,Birmingham,Sushi Spot,Japanese,Sarah Chen,Bicycle,2024-02-22,39.00,21,Cancelled,NaN,NaN
1,ORD0002,Noah Smith,London,Burger Barn,American,Sarah Chen,Bicycle,2024-09-15,35.30,35,Cancelled,NaN,NaN
2,ORD0003,Noah Chen,Leeds,Noodle Bar,Chinese,James Patel,Bicycle,2024-03-22,40.06,53,Completed,NaN,NaN
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
4,ORD0005,Ravi Williams,Bristol,The Curry House,Indian,Tom Walsh,Bicycle,2024-12-26,8.94,39,Completed,4.0,"Great food, fast delivery!"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,ORD0146,Hassan Jones,Bristol,The Curry House,Indian,Sarah Chen,Bicycle,2024-06-29,32.53,32,Completed,5.0,Really happy with this order.
146,ORD0147,Emma Jones,Leeds,Spice Garden,Indian,James Patel,Bicycle,2024-01-23,44.66,15,Completed,1.0,Very late.
147,ORD0148,Ravi Ahmed,Birmingham,Spice Garden,Indian,Sarah Chen,Scooter,2024-07-01,48.18,16,Completed,5.0,Will order again.
148,ORD0149,Maya Ahmed,Leeds,The Curry House,Indian,Sarah Chen,Scooter,2024-12-20,30.13,44,Completed,3.0,Average experience.
149,ORD0150,Tom Patel,Bristol,Taco Town,Mexican,James Patel,Bicycle,2024-02-10,21.73,47,Completed,5.0,Really happy with this order.

### Exploration sequence — run each cell and observe

Before doing any analysis, spend time understanding the shape and structure of the data. Run each cell and read what it tells you.

In [2]:
# First five rows — a quick preview
df.head()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
0,ORD0001,David Smith,Birmingham,Sushi Spot,Japanese,Sarah Chen,Bicycle,2024-02-22,39.00,21,Cancelled,NaN,NaN
1,ORD0002,Noah Smith,London,Burger Barn,American,Sarah Chen,Bicycle,2024-09-15,35.30,35,Cancelled,NaN,NaN
2,ORD0003,Noah Chen,Leeds,Noodle Bar,Chinese,James Patel,Bicycle,2024-03-22,40.06,53,Completed,NaN,NaN
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
4,ORD0005,Ravi Williams,Bristol,The Curry House,Indian,Tom Walsh,Bicycle,2024-12-26,8.94,39,Completed,4.0,"Great food, fast delivery!"

In [3]:
# Last five rows — check the end of the data too
df.tail()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
145,ORD0146,Hassan Jones,Bristol,The Curry House,Indian,Sarah Chen,Bicycle,2024-06-29,32.53,32,Completed,5.0,Really happy with this order.
146,ORD0147,Emma Jones,Leeds,Spice Garden,Indian,James Patel,Bicycle,2024-01-23,44.66,15,Completed,1.0,Very late.
147,ORD0148,Ravi Ahmed,Birmingham,Spice Garden,Indian,Sarah Chen,Scooter,2024-07-01,48.18,16,Completed,5.0,Will order again.
148,ORD0149,Maya Ahmed,Leeds,The Curry House,Indian,Sarah Chen,Scooter,2024-12-20,30.13,44,Completed,3.0,Average experience.
149,ORD0150,Tom Patel,Bristol,Taco Town,Mexican,James Patel,Bicycle,2024-02-10,21.73,47,Completed,5.0,Really happy with this order.

In [4]:
# Shape: (rows, columns) as a tuple
df.shape

(150, 13)

In [5]:
# Column names, data types, and non-null counts
# Notice: which column has fewer non-null values than the others?
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            150 non-null    str
 1   customer_name       150 non-null    str
 2   customer_city       150 non-null    str
 3   restaurant_name     150 non-null    str
 4   cuisine_type        150 non-null    str
 5   driver_name         150 non-null    str
 6   vehicle_type        150 non-null    str
 7   order_date          150 non-null    str
 8   order_total         150 non-null    float64
 9   delivery_time_mins  150 non-null    int64
 10  status              150 non-null    str
 11  rating              98 non-null     float64
 12  review_text         98 non-null     str
dtypes: float64(2), int64(1), str(10)
memory usage: 28.7 KB

In [6]:
# Summary statistics on numeric columns
# What does it tell you? What doesn't it tell you?
df.describe()

       order_total  delivery_time_mins     rating
count   150.000000          150.000000  98.000000
mean     30.396867           41.906667   3.795918
std      15.198267           18.894744   1.243202
min       5.680000           10.000000   1.000000
25%      16.525000           26.000000   3.000000
50%      29.235000           41.000000   4.000000
75%      44.615000           60.000000   5.000000
max      55.000000           75.000000   5.000000

### Exercise 1 — explore and describe

Using the exploration methods above, answer these questions in the commentary cell below:

1. How many orders are in the dataset?
2. Which columns have missing values, and roughly how many?
3. What is the average order total, and what is the range (min to max)?
4. What does `.info()` tell you that `.describe()` doesn't — and vice versa?

### Commentary cell 1

1. What is a DataFrame? How does it differ from a list?
2. Answer the four questions from Exercise 1 above.
3. What did the exploration methods tell you about this dataset before you've done any analysis?

*Your commentary here*

---
## Part 2 — Selecting columns

### Single column — returns a Series

In [7]:
# Selecting one column returns a Series — a single column with an index
df["restaurant_name"]

0           Sushi Spot
1          Burger Barn
2           Noodle Bar
3         Bella Napoli
4      The Curry House
            ...
145    The Curry House
146       Spice Garden
147       Spice Garden
148    The Curry House
149          Taco Town
Name: restaurant_name, Length: 150, dtype: str

In [8]:
# Numeric Series — same idea
df["order_total"]

0      39.00
1      35.30
2      40.06
3      35.38
4       8.94
       ...
145    32.53
146    44.66
147    48.18
148    30.13
149    21.73
Name: order_total, Length: 150, dtype: float64

### Multiple columns — returns a DataFrame

Note the double brackets. The outer `[ ]` selects from the DataFrame. The inner `[ ]` is a Python list of column names. This trips people up — take a moment with it.

In [9]:
# Double brackets — list of column names inside the selection
df[["customer_name", "restaurant_name", "order_total"]]

     customer_name  restaurant_name  order_total
0      David Smith       Sushi Spot        39.00
1       Noah Smith      Burger Barn        35.30
2        Noah Chen       Noodle Bar        40.06
3      Kavya Jones     Bella Napoli        35.38
4    Ravi Williams  The Curry House         8.94
..             ...              ...          ...
145   Hassan Jones  The Curry House        32.53
146     Emma Jones     Spice Garden        44.66
147     Ravi Ahmed     Spice Garden        48.18
148     Maya Ahmed  The Curry House        30.13
149      Tom Patel        Taco Town        21.73

[150 rows x 3 columns]

In [10]:
# value_counts() — quick frequency count on a column
# How many orders from each cuisine type?
df["cuisine_type"].value_counts()

cuisine_type
American    33
Italian     32
Indian      29
Chinese     28
Mexican     15
Japanese    13
Name: count, dtype: int64

### Exercise 2 — column selection

1. Select just the `cuisine_type` column and print the first 10 values using `.head(10)`
2. Select `restaurant_name`, `order_total`, and `rating` together
3. Use `.value_counts()` on the `status` column — how many orders have each status?
4. Use `.value_counts()` on the `vehicle_type` column

In [ ]:
# 1 — cuisine_type, first 10
df["cuisine_type"].head(10)

0    Japanese
1    American
2     Chinese
3     Italian
4      Indian
5      Indian
6     Italian
7    Japanese
8    American
9    American
Name: cuisine_type, dtype: str

In [ ]:
# 2 — three columns together
df[["restaurant_name", "order_total", "cuisine_type"]]

     restaurant_name  order_total cuisine_type
0         Sushi Spot        39.00     Japanese
1        Burger Barn        35.30     American
2         Noodle Bar        40.06      Chinese
3       Bella Napoli        35.38      Italian
4    The Curry House         8.94       Indian
..               ...          ...          ...
145  The Curry House        32.53       Indian
146     Spice Garden        44.66       Indian
147     Spice Garden        48.18       Indian
148  The Curry House        30.13       Indian
149        Taco Town        21.73      Mexican

[150 rows x 3 columns]

In [36]:
# 3 — status value counts
df["status"].value_counts()

status
Completed    114
Cancelled     36
Name: count, dtype: int64

In [40]:
# 4 — vehicle_type value counts
df["vehicle_type"].value_counts()

vehicle_type
Car        52
Scooter    51
Bicycle    47
Name: count, dtype: int64

**Stretch:** Use `.value_counts()` on `customer_city`. What does this tell you about the QuickBite customer base?

In [42]:
# Stretch
df["customer_city"].value_counts()

customer_city
London        42
Leeds         40
Birmingham    26
Bristol       25
Manchester    17
Name: count, dtype: int64

In [54]:
df[["customer_city"]]

    customer_city
0      Birmingham
1          London
2           Leeds
3          London
4         Bristol
..            ...
145       Bristol
146         Leeds
147    Birmingham
148         Leeds
149       Bristol

[150 rows x 1 columns]

### Commentary cell 2

1. What is the difference between `df["column"]` and `df[["column"]]`? What does each return?
2. What does a Series look like compared to a DataFrame?
3. What did `.value_counts()` reveal that you couldn't see just by looking at the raw data?

*Your commentary here*

---
## Part 3 — Filtering rows

### The boolean mask — two steps made visible

Filtering works by creating a Series of `True`/`False` values (the mask), then passing that into `df[...]` to keep only the `True` rows. Let's make both steps visible.

In [11]:
# Step 1: create the mask — a Series of True/False
mask = df["customer_city"] == "London"
mask.head(10)

0    False
1     True
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9     True
Name: customer_city, dtype: bool

In [12]:
# Step 2: apply the mask — keep only True rows
london_orders = df[mask]
london_orders.shape

(42, 13)

In [16]:
# In practice, both steps are combined into one line
london_orders = df[df["customer_city"] == "London"]
london_orders.head()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
1,ORD0002,Noah Smith,London,Burger Barn,American,Sarah Chen,Bicycle,2024-09-15,35.30,35,Cancelled,NaN,NaN
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
7,ORD0008,Maya Williams,London,Sushi Spot,Japanese,Tom Walsh,Car,2024-06-10,16.03,73,Completed,5.0,Really happy with this order.
9,ORD0010,Priya Jones,London,Burger Barn,American,Sarah Chen,Car,2024-03-22,44.71,64,Cancelled,NaN,NaN
12,ORD0013,Faisal Davis,London,Taco Town,Mexican,Tom Walsh,Car,2024-04-11,13.07,30,Cancelled,NaN,NaN

In [17]:
# Numeric filter
high_value = df[df["order_total"] > 30]
print(f"Orders over £30: {high_value.shape[0]}")

Orders over £30: 74

### Multiple conditions — the parentheses rule

When combining conditions, each one must be wrapped in its own parentheses. Without them, Python's operator precedence causes a confusing error. Use `&` for AND and `|` for OR — not `and` / `or`.

In [18]:
# Both conditions must be True — & operator, parentheses around each
london_high = df[(df["customer_city"] == "London") & (df["order_total"] > 30)]
print(f"London orders over £30: {london_high.shape[0]}")

London orders over £30: 19

### Exercise 3 — filtering

1. Filter to only completed orders
2. Filter to only Italian restaurants
3. Filter to orders with a rating of 5
4. Filter to London orders with an order total over £25
5. Filter to orders where delivery time was over 45 minutes — how many are there?

In [41]:
# 1 — completed orders
df[df["status"] == "Completed"]

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
2,ORD0003,Noah Chen,Leeds,Noodle Bar,Chinese,James Patel,Bicycle,2024-03-22,40.06,53,Completed,NaN,NaN
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
4,ORD0005,Ravi Williams,Bristol,The Curry House,Indian,Tom Walsh,Bicycle,2024-12-26,8.94,39,Completed,4.0,"Great food, fast delivery!"
5,ORD0006,Maya Williams,Leeds,The Curry House,Indian,Sarah Chen,Scooter,2024-06-30,15.87,44,Completed,4.0,"Hot food, on time."
6,ORD0007,Hassan Patel,Leeds,Bella Napoli,Italian,James Patel,Car,2024-12-18,33.07,51,Completed,3.0,Fine.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,ORD0146,Hassan Jones,Bristol,The Curry House,Indian,Sarah Chen,Bicycle,2024-06-29,32.53,32,Completed,5.0,Really happy with this order.
146,ORD0147,Emma Jones,Leeds,Spice Garden,Indian,James Patel,Bicycle,2024-01-23,44.66,15,Completed,1.0,Very late.
147,ORD0148,Ravi Ahmed,Birmingham,Spice Garden,Indian,Sarah Chen,Scooter,2024-07-01,48.18,16,Completed,5.0,Will order again.
148,ORD0149,Maya Ahmed,Leeds,The Curry House,Indian,Sarah Chen,Scooter,2024-12-20,30.13,44,Completed,3.0,Average experience.
149,ORD0150,Tom Patel,Bristol,Taco Town,Mexican,James Patel,Bicycle,2024-02-10,21.73,47,Completed,5.0,Really happy with this order.

In [46]:
# 2 — Italian restaurants
italian_restaurants = df[df["cuisine_type"] == "Italian"]
print(f"Italian restaurants: {italian_restaurants.shape[0]}")

Italian restaurants: 32

In [44]:
# 3 — rating of 5
df[df["rating"]==5]

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
7,ORD0008,Maya Williams,London,Sushi Spot,Japanese,Tom Walsh,Car,2024-06-10,16.03,73,Completed,5.0,Really happy with this order.
15,ORD0016,Faisal Williams,Bristol,Noodle Bar,Chinese,Aisha Kofi,Bicycle,2024-10-03,42.89,35,Completed,5.0,Will order again.
19,ORD0020,David Taylor,Birmingham,Bella Napoli,Italian,Aisha Kofi,Scooter,2024-01-28,38.83,22,Completed,5.0,"Great food, fast delivery!"
21,ORD0022,Ravi Jones,London,The Grill,American,Marcus Obi,Bicycle,2024-05-01,13.73,72,Completed,5.0,"Great food, fast delivery!"
34,ORD0035,Alice Patel,Birmingham,Bella Napoli,Italian,Sarah Chen,Scooter,2024-03-22,44.48,23,Completed,5.0,Really happy with this order.
38,ORD0039,Bob Taylor,London,The Grill,American,Tom Walsh,Car,2024-12-09,15.25,65,Completed,5.0,"Hot food, on time."
40,ORD0041,Emma Chen,Leeds,Bella Napoli,Italian,Sarah Chen,Car,2024-10-18,20.40,10,Completed,5.0,"Hot food, on time."
44,ORD0045,Alice Jones,Leeds,Sushi Spot,Japanese,Sarah Chen,Car,2024-09-22,28.50,41,Completed,5.0,"Hot food, on time."
45,ORD0046,Ravi Wilson,Birmingham,Dragon Palace,Chinese,Tom Walsh,Car,2024-09-15,26.62,67,Completed,5.0,Will order again.
46,ORD0047,Isla Chen,Birmingham,The Grill,American,Aisha Kofi,Car,2024-05-02,19.09,19,Completed,5.0,Driver was very friendly.
47,ORD0048,Ravi Jones,Manchester,Pizza Palace,Italian,Sarah Chen,Scooter,2024-12-21,13.06,37,Completed,5.0,"Hot food, on time."
49,ORD0050,Maya Ahmed,London,The Curry House,Indian,James Patel,Scooter,2024-08-02,32.14,38,Completed,5.0,Will order again.
51,ORD0052,Noah Patel,Leeds,Pizza Palace,Italian,Marcus Obi,Scooter,2024-07-13,21.70,68,Completed,5.0,Driver was very friendly.
59,ORD0060,Sophie Wilson,Leeds,The Curry House,Indian,Marcus Obi,Scooter,2024-06-15,14.50,37,Completed,5.0,Driver was very friendly.
66,ORD0067,Jack Ahmed,Leeds,Dragon Palace,Chinese,James Patel,Bicycle,2024-01-27,18.00,71,Completed,5.0,Will order again.
67,ORD0068,Carol Wilson,London,Pizza Palace,Italian,Sarah Chen,Car,2024-06-04,9.72,41,Completed,5.0,"Hot food, on time."
72,ORD0073,Olivia Jones,Leeds,Taco Town,Mexican,Aisha Kofi,Scooter,2024-09-13,32.23,66,Completed,5.0,Driver was very friendly.
74,ORD0075,Quinn Ahmed,Birmingham,Pizza Palace,Italian,Tom Walsh,Scooter,2024-11-21,45.81,21,Completed,5.0,Driver was very friendly.
77,ORD0078,Quinn Brown,Bristol,Dragon Palace,Chinese,Aisha Kofi,Bicycle,2024-04-14,18.72,26,Completed,5.0,"Great food, fast delivery!"
85,ORD0086,Priya Williams,Birmingham,Noodle Bar,Chinese,Aisha Kofi,Car,2024-02-11,47.66,58,Completed,5.0,"Hot food, on time."
90,ORD0091,Olivia Brown,Bristol,Taco Town,Mexican,Aisha Kofi,Car,2024-05-08,28.11,48,Completed,5.0,"Great food, fast delivery!"
93,ORD0094,Isla Patel,London,Spice Garden,Indian,James Patel,Scooter,2024-01-18,34.19,26,Completed,5.0,Will order again.
94,ORD0095,Faisal Chen,Manchester,The Grill,American,James Patel,Car,2024-09-13,50.72,31,Completed,5.0,Driver was very friendly.
106,ORD0107,Quinn Williams,Leeds,Spice Garden,Indian,Marcus Obi,Scooter,2024-07-24,26.60,23,Completed,5.0,"Great food, fast delivery!"
109,ORD0110,Kavya Ahmed,Leeds,Bella Napoli,Italian,Marcus Obi,Scooter,2024-08-06,20.97,42,Completed,5.0,"Great food, fast delivery!"
112,ORD0113,Liam Jones,Bristol,The Grill,American,Sarah Chen,Bicycle,2024-12-02,29.37,23,Completed,5.0,"Great food, fast delivery!"
115,ORD0116,Maya Jones,Manchester,Spice Garden,Indian,Marcus Obi,Car,2024-09-28,16.15,63,Completed,5.0,Driver was very friendly.
116,ORD0117,Kavya Wilson,Bristol,Burger Barn,American,Marcus Obi,Bicycle,2024-03-21,42.84,16,Completed,5.0,Will order again.
125,ORD0126,Sophie Wilson,Birmingham,The Curry House,Indian,Sarah Chen,Scooter,2024-02-04,28.71,48,Completed,5.0,"Hot food, on time."
128,ORD0129,Emma Smith,Leeds,Burger Barn,American,James Patel,Car,2024-02-13,30.48,32,Completed,5.0,Will order again.
135,ORD0136,Liam Chen,Leeds,Noodle Bar,Chinese,James Patel,Car,2024-08-17,17.08,40,Completed,5.0,Really happy with this order.
138,ORD0139,Quinn Patel,Leeds,Burger Barn,American,Sarah Chen,Scooter,2024-06-27,51.56,63,Completed,5.0,Really happy with this order.
145,ORD0146,Hassan Jones,Bristol,The Curry House,Indian,Sarah Chen,Bicycle,2024-06-29,32.53,32,Completed,5.0,Really happy with this order.
147,ORD0148,Ravi Ahmed,Birmingham,Spice Garden,Indian,Sarah Chen,Scooter,2024-07-01,48.18,16,Completed,5.0,Will order again.
149,ORD0150,Tom Patel,Bristol,Taco Town,Mexican,James Patel,Bicycle,2024-02-10,21.73,47,Completed,5.0,Really happy with this order.

In [52]:
# 4 — London orders over £25
df[(df["order_total"] > 25) & (df["customer_city"] == "London")]

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
1,ORD0002,Noah Smith,London,Burger Barn,American,Sarah Chen,Bicycle,2024-09-15,35.30,35,Cancelled,NaN,NaN
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
9,ORD0010,Priya Jones,London,Burger Barn,American,Sarah Chen,Car,2024-03-22,44.71,64,Cancelled,NaN,NaN
17,ORD0018,Hassan Smith,London,Spice Garden,Indian,Sarah Chen,Bicycle,2024-01-17,48.05,19,Cancelled,NaN,NaN
22,ORD0023,Faisal Taylor,London,Bella Napoli,Italian,James Patel,Scooter,2024-05-26,26.44,72,Completed,4.0,"Great food, fast delivery!"
23,ORD0024,Sophie Davis,London,The Curry House,Indian,Marcus Obi,Bicycle,2024-10-26,29.10,30,Completed,3.0,"OK, nothing special."
26,ORD0027,Olivia Brown,London,Spice Garden,Indian,Aisha Kofi,Car,2024-10-15,54.81,19,Cancelled,NaN,NaN
48,ORD0049,Olivia Taylor,London,Sushi Spot,Japanese,Aisha Kofi,Scooter,2024-10-26,52.33,12,Cancelled,NaN,NaN
49,ORD0050,Maya Ahmed,London,The Curry House,Indian,James Patel,Scooter,2024-08-02,32.14,38,Completed,5.0,Will order again.
53,ORD0054,Hassan Chen,London,Noodle Bar,Chinese,Sarah Chen,Bicycle,2024-03-05,28.94,24,Cancelled,NaN,NaN
57,ORD0058,Noah Ahmed,London,Bella Napoli,Italian,James Patel,Car,2024-08-23,40.51,65,Completed,4.0,"Hot food, on time."
61,ORD0062,Priya Ahmed,London,Burger Barn,American,James Patel,Bicycle,2024-07-26,39.74,49,Cancelled,NaN,NaN
63,ORD0064,Grace Brown,London,The Grill,American,Sarah Chen,Bicycle,2024-04-20,42.06,45,Cancelled,NaN,NaN
73,ORD0074,Tom Williams,London,Burger Barn,American,Sarah Chen,Car,2024-10-21,34.56,12,Completed,4.0,Will order again.
76,ORD0077,Isla Brown,London,Bella Napoli,Italian,Tom Walsh,Bicycle,2024-12-02,48.53,69,Completed,NaN,NaN
86,ORD0087,Bob Wilson,London,Sushi Spot,Japanese,James Patel,Bicycle,2024-02-16,26.98,22,Completed,4.0,"Great food, fast delivery!"
93,ORD0094,Isla Patel,London,Spice Garden,Indian,James Patel,Scooter,2024-01-18,34.19,26,Completed,5.0,Will order again.
97,ORD0098,Maya Brown,London,Sushi Spot,Japanese,Aisha Kofi,Bicycle,2024-11-13,49.27,51,Cancelled,NaN,NaN
102,ORD0103,Grace Wilson,London,Spice Garden,Indian,James Patel,Bicycle,2024-03-05,44.46,36,Completed,1.0,Food was cold.
105,ORD0106,Noah Davis,London,Burger Barn,American,Aisha Kofi,Scooter,2024-07-04,30.91,23,Completed,2.0,Took too long.
110,ORD0111,Carol Jones,London,Bella Napoli,Italian,Marcus Obi,Car,2024-07-09,45.68,17,Cancelled,NaN,NaN
120,ORD0121,Ravi Brown,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-01-10,28.26,19,Completed,2.0,Very late.
121,ORD0122,Noah Williams,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-03-28,45.17,68,Completed,NaN,NaN
131,ORD0132,Emma Brown,London,Noodle Bar,Chinese,Sarah Chen,Scooter,2024-06-07,53.40,60,Completed,3.0,Fine.

In [65]:
# 5 — delivery time over 45 minutes
slow_deliveries = df[df["delivery_time_mins"] > 45]
print(f"there are {slow_deliveries.shape[0]} deliveries over 45 minute deliveries")

there are 61 deliveries over 45 minute deliveries

**Stretch:** Filter to orders that are either cancelled OR have a rating below 3. Use `|`. How many rows?

In [73]:
# Stretch — | operator
df[(df["status"] == "Cancelled") | (df["rating"] < 3)] .shape[0]

53

In [80]:

broken = df[(df["customer_city"] == "London") & (df["order_total"] > 20)]
broken #para apareçer o df temos que escrever"broken" ou o que estiver antes do =

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
1,ORD0002,Noah Smith,London,Burger Barn,American,Sarah Chen,Bicycle,2024-09-15,35.30,35,Cancelled,NaN,NaN
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
9,ORD0010,Priya Jones,London,Burger Barn,American,Sarah Chen,Car,2024-03-22,44.71,64,Cancelled,NaN,NaN
17,ORD0018,Hassan Smith,London,Spice Garden,Indian,Sarah Chen,Bicycle,2024-01-17,48.05,19,Cancelled,NaN,NaN
22,ORD0023,Faisal Taylor,London,Bella Napoli,Italian,James Patel,Scooter,2024-05-26,26.44,72,Completed,4.0,"Great food, fast delivery!"
23,ORD0024,Sophie Davis,London,The Curry House,Indian,Marcus Obi,Bicycle,2024-10-26,29.10,30,Completed,3.0,"OK, nothing special."
26,ORD0027,Olivia Brown,London,Spice Garden,Indian,Aisha Kofi,Car,2024-10-15,54.81,19,Cancelled,NaN,NaN
48,ORD0049,Olivia Taylor,London,Sushi Spot,Japanese,Aisha Kofi,Scooter,2024-10-26,52.33,12,Cancelled,NaN,NaN
49,ORD0050,Maya Ahmed,London,The Curry House,Indian,James Patel,Scooter,2024-08-02,32.14,38,Completed,5.0,Will order again.
53,ORD0054,Hassan Chen,London,Noodle Bar,Chinese,Sarah Chen,Bicycle,2024-03-05,28.94,24,Cancelled,NaN,NaN
56,ORD0057,David Wilson,London,The Curry House,Indian,Tom Walsh,Scooter,2024-12-04,23.84,74,Completed,NaN,NaN
57,ORD0058,Noah Ahmed,London,Bella Napoli,Italian,James Patel,Car,2024-08-23,40.51,65,Completed,4.0,"Hot food, on time."
61,ORD0062,Priya Ahmed,London,Burger Barn,American,James Patel,Bicycle,2024-07-26,39.74,49,Cancelled,NaN,NaN
63,ORD0064,Grace Brown,London,The Grill,American,Sarah Chen,Bicycle,2024-04-20,42.06,45,Cancelled,NaN,NaN
73,ORD0074,Tom Williams,London,Burger Barn,American,Sarah Chen,Car,2024-10-21,34.56,12,Completed,4.0,Will order again.
76,ORD0077,Isla Brown,London,Bella Napoli,Italian,Tom Walsh,Bicycle,2024-12-02,48.53,69,Completed,NaN,NaN
86,ORD0087,Bob Wilson,London,Sushi Spot,Japanese,James Patel,Bicycle,2024-02-16,26.98,22,Completed,4.0,"Great food, fast delivery!"
93,ORD0094,Isla Patel,London,Spice Garden,Indian,James Patel,Scooter,2024-01-18,34.19,26,Completed,5.0,Will order again.
97,ORD0098,Maya Brown,London,Sushi Spot,Japanese,Aisha Kofi,Bicycle,2024-11-13,49.27,51,Cancelled,NaN,NaN
102,ORD0103,Grace Wilson,London,Spice Garden,Indian,James Patel,Bicycle,2024-03-05,44.46,36,Completed,1.0,Food was cold.
105,ORD0106,Noah Davis,London,Burger Barn,American,Aisha Kofi,Scooter,2024-07-04,30.91,23,Completed,2.0,Took too long.
110,ORD0111,Carol Jones,London,Bella Napoli,Italian,Marcus Obi,Car,2024-07-09,45.68,17,Cancelled,NaN,NaN
119,ORD0120,Kavya Jones,London,Dragon Palace,Chinese,Aisha Kofi,Bicycle,2024-03-07,24.32,39,Cancelled,NaN,NaN
120,ORD0121,Ravi Brown,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-01-10,28.26,19,Completed,2.0,Very late.
121,ORD0122,Noah Williams,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-03-28,45.17,68,Completed,NaN,NaN
130,ORD0131,Bob Brown,London,The Curry House,Indian,Marcus Obi,Car,2024-12-13,24.63,42,Cancelled,NaN,NaN
131,ORD0132,Emma Brown,London,Noodle Bar,Chinese,Sarah Chen,Scooter,2024-06-07,53.40,60,Completed,3.0,Fine.

### Commentary cell 3

1. What is a boolean mask? Describe in plain English what happens when you write `df[df["col"] == "value"]`.
2. Why do you need parentheses around each condition when combining filters with `&` or `|`?
3. The bug cell produced `ValueError: The truth value of a Series is ambiguous`. What does that mean, and why does `&` fix it where `and` fails?

*Your commentary here*

---
## Part 4 — Sorting

In [81]:
# Sort ascending (default)
df.sort_values("order_total").head()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
30,ORD0031,Priya Williams,London,Burger Barn,American,Aisha Kofi,Scooter,2024-01-23,5.68,26,Completed,NaN,NaN
114,ORD0115,Isla Smith,Manchester,Taco Town,Mexican,James Patel,Scooter,2024-06-28,5.80,28,Cancelled,NaN,NaN
118,ORD0119,Quinn Williams,London,Sushi Spot,Japanese,Aisha Kofi,Car,2024-01-29,5.88,48,Completed,4.0,Driver was very friendly.
89,ORD0090,Emma Chen,Leeds,Taco Town,Mexican,Aisha Kofi,Scooter,2024-12-07,5.97,69,Completed,4.0,"Great food, fast delivery!"
84,ORD0085,Sophie Brown,London,Dragon Palace,Chinese,Marcus Obi,Car,2024-08-21,6.26,28,Completed,4.0,"Great food, fast delivery!"

In [82]:
# Sort descending
df.sort_values("order_total", ascending=False).head()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
133,ORD0134,Jack Patel,Manchester,The Curry House,Indian,Aisha Kofi,Bicycle,2024-04-25,55.00,29,Completed,3.0,Decent enough.
26,ORD0027,Olivia Brown,London,Spice Garden,Indian,Aisha Kofi,Car,2024-10-15,54.81,19,Cancelled,NaN,NaN
37,ORD0038,David Wilson,Leeds,The Curry House,Indian,James Patel,Scooter,2024-11-06,54.22,24,Completed,4.0,Driver was very friendly.
144,ORD0145,Ravi Smith,Leeds,Dragon Palace,Chinese,Marcus Obi,Car,2024-07-17,54.06,42,Completed,3.0,Fine.
83,ORD0084,Bob Brown,Leeds,Bella Napoli,Italian,Aisha Kofi,Car,2024-11-29,54.05,73,Completed,NaN,NaN

In [ ]:
# Top 10 slowest deliveries
df.sort_values("delivery_time_mins", ascending=False).head(10)

### Exercise 4 — sorting

1. Sort by `rating`, descending — which orders have the highest ratings?
2. Sort by `delivery_time_mins`, ascending — which orders were fastest?
3. Sort by `order_total`, descending — show only the top 5

In [89]:
# 1
df.sort_values("rating", ascending=False).head()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
3,ORD0004,Kavya Jones,London,Bella Napoli,Italian,Marcus Obi,Scooter,2024-06-25,35.38,15,Completed,5.0,"Great food, fast delivery!"
7,ORD0008,Maya Williams,London,Sushi Spot,Japanese,Tom Walsh,Car,2024-06-10,16.03,73,Completed,5.0,Really happy with this order.
45,ORD0046,Ravi Wilson,Birmingham,Dragon Palace,Chinese,Tom Walsh,Car,2024-09-15,26.62,67,Completed,5.0,Will order again.
15,ORD0016,Faisal Williams,Bristol,Noodle Bar,Chinese,Aisha Kofi,Bicycle,2024-10-03,42.89,35,Completed,5.0,Will order again.
19,ORD0020,David Taylor,Birmingham,Bella Napoli,Italian,Aisha Kofi,Scooter,2024-01-28,38.83,22,Completed,5.0,"Great food, fast delivery!"

In [91]:
# 2
df.sort_values("delivery_time_mins").head()

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
40,ORD0041,Emma Chen,Leeds,Bella Napoli,Italian,Sarah Chen,Car,2024-10-18,20.40,10,Completed,5.0,"Hot food, on time."
10,ORD0011,Carol Taylor,Leeds,Noodle Bar,Chinese,Aisha Kofi,Car,2024-05-08,53.57,11,Completed,1.0,Missing items.
65,ORD0066,Bob Smith,Bristol,Taco Town,Mexican,Sarah Chen,Car,2024-09-08,10.58,11,Cancelled,NaN,NaN
48,ORD0049,Olivia Taylor,London,Sushi Spot,Japanese,Aisha Kofi,Scooter,2024-10-26,52.33,12,Cancelled,NaN,NaN
73,ORD0074,Tom Williams,London,Burger Barn,American,Sarah Chen,Car,2024-10-21,34.56,12,Completed,4.0,Will order again.

In [92]:
# 3
df.sort_values("order_total", ascending=False).head(5)

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
133,ORD0134,Jack Patel,Manchester,The Curry House,Indian,Aisha Kofi,Bicycle,2024-04-25,55.00,29,Completed,3.0,Decent enough.
26,ORD0027,Olivia Brown,London,Spice Garden,Indian,Aisha Kofi,Car,2024-10-15,54.81,19,Cancelled,NaN,NaN
37,ORD0038,David Wilson,Leeds,The Curry House,Indian,James Patel,Scooter,2024-11-06,54.22,24,Completed,4.0,Driver was very friendly.
144,ORD0145,Ravi Smith,Leeds,Dragon Palace,Chinese,Marcus Obi,Car,2024-07-17,54.06,42,Completed,3.0,Fine.
83,ORD0084,Bob Brown,Leeds,Bella Napoli,Italian,Aisha Kofi,Car,2024-11-29,54.05,73,Completed,NaN,NaN

**Stretch:** Sort by `cuisine_type` ascending, then by `order_total` descending within each cuisine:
```python
df.sort_values(["cuisine_type", "order_total"], ascending=[True, False])
```

In [97]:
# Stretch
df.sort_values(["cuisine_type","order_total"], ascending=[True,False]).head(10)

,order_id,customer_name,customer_city,restaurant_name,cuisine_type,driver_name,vehicle_type,order_date,order_total,delivery_time_mins,status,rating,review_text
31,ORD0032,Olivia Davis,Leeds,The Grill,American,Marcus Obi,Bicycle,2024-02-08,52.28,29,Cancelled,NaN,NaN
111,ORD0112,Ravi Davis,Birmingham,Burger Barn,American,Aisha Kofi,Scooter,2024-12-06,52.09,64,Completed,2.0,Missing items.
82,ORD0083,Priya Brown,Birmingham,The Grill,American,Tom Walsh,Scooter,2024-08-21,51.68,34,Completed,4.0,Will order again.
138,ORD0139,Quinn Patel,Leeds,Burger Barn,American,Sarah Chen,Scooter,2024-06-27,51.56,63,Completed,5.0,Really happy with this order.
94,ORD0095,Faisal Chen,Manchester,The Grill,American,James Patel,Car,2024-09-13,50.72,31,Completed,5.0,Driver was very friendly.
36,ORD0037,Liam Davis,Leeds,The Grill,American,James Patel,Bicycle,2024-02-29,48.91,43,Completed,4.0,"Great food, fast delivery!"
137,ORD0138,Bob Ahmed,Birmingham,The Grill,American,Marcus Obi,Car,2024-09-21,47.63,46,Completed,4.0,Will order again.
9,ORD0010,Priya Jones,London,Burger Barn,American,Sarah Chen,Car,2024-03-22,44.71,64,Cancelled,NaN,NaN
80,ORD0081,Maya Chen,Bristol,The Grill,American,Sarah Chen,Bicycle,2024-05-21,43.75,63,Completed,1.0,Missing items.
116,ORD0117,Kavya Wilson,Bristol,Burger Barn,American,Marcus Obi,Bicycle,2024-03-21,42.84,16,Completed,5.0,Will order again.

### Commentary cell 4

1. Does sorting a DataFrame change the original data, or create a new view? How would you check?
2. When would sorting be useful as a step before doing further analysis?

*Your commentary here*

---
## Part 5 — Aggregation with groupby

*(Session 2)*

This is the payoff. `groupby` splits your data into groups and lets you compute a summary for each one. Questions you couldn't answer by looking at 150 rows become answerable in a single line.

In [98]:
# Average order total by cuisine type
# groupby splits the data | ["order_total"] selects the column | .mean() aggregates
df.groupby("cuisine_type")["order_total"].mean()

cuisine_type
American    32.873636
Chinese     28.818214
Indian      30.765517
Italian     36.692188
Japanese    26.161538
Mexican     17.422667
Name: order_total, dtype: float64

In [103]:
# Different aggregations on the same groupby
print(df.groupby("cuisine_type")["order_total"].sum())
print()
print(df.groupby("cuisine_type")["order_total"].count())

cuisine_type
American    1084.83
Chinese      806.91
Indian       892.20
Italian     1174.15
Japanese     340.10
Mexican      261.34
Name: order_total, dtype: float64

cuisine_type
American    33
Chinese     28
Indian      29
Italian     32
Japanese    13
Mexican     15
Name: order_total, dtype: int64

In [100]:
# Chaining: groupby then sort — highest rated cuisine first
# Note: .mean() on rating ignores NaN values automatically
df.groupby("cuisine_type")["rating"].mean().sort_values(ascending=False)

cuisine_type
Italian     4.047619
Japanese    4.000000
Indian      3.894737
American    3.782609
Chinese     3.600000
Mexican     3.333333
Name: rating, dtype: float64

### Exercise 5 — groupby

1. What is the average delivery time by city?
2. Which restaurant has the highest average rating?
3. How many orders has each driver completed? (use `.count()`)
4. What is the average order total by cuisine type, sorted highest to lowest?
5. What is the average rating by vehicle type?

In [120]:
# 1 — average delivery time by city
df.groupby("customer_city")["delivery_time_mins"].mean()

customer_city
Birmingham    40.615385
Bristol       41.720000
Leeds         42.100000
London        42.095238
Manchester    43.235294
Name: delivery_time_mins, dtype: float64

In [125]:
# 2 — highest average rating by restaurant
df.groupby("restaurant_name")["rating"].mean().sort_values(ascending=False)

restaurant_name
Bella Napoli       4.071429
Pizza Palace       4.000000
The Curry House    4.000000
The Grill          4.000000
Sushi Spot         4.000000
Spice Garden       3.714286
Dragon Palace      3.636364
Noodle Bar         3.555556
Burger Barn        3.444444
Taco Town          3.333333
Name: rating, dtype: float64

In [126]:
# 3 — order count per driver
df.groupby("driver_name")["order_id"].count()

driver_name
Aisha Kofi     31
James Patel    28
Marcus Obi     26
Sarah Chen     42
Tom Walsh      23
Name: order_id, dtype: int64

In [ ]:
# 4 — average order total by cuisine, sorted

In [ ]:
# 5 — average rating by vehicle type

**Stretch 1:** Multiple aggregations in one groupby:

In [ ]:
# Stretch 1
df.groupby("customer_city").agg({
    "order_total": "mean",
    "delivery_time_mins": "mean",
    "rating": "mean"
})

In [ ]:
# Stretch 2: filter to completed orders first, then run groupby
# Does the result differ from running groupby on the full dataset? Why?

### Commentary cell 5

1. What does `.groupby()` actually do to the data — describe it step by step in plain English.
2. What is the difference between `.count()` and `.mean()` in a groupby context?
3. What business question did Exercise 5 answer that you couldn't have answered by looking at the raw CSV?

*Your commentary here*

---
## Part 6 — Missing data (awareness demo)

Real data always has gaps. Run these two cells and observe — no exercise this week, but this will come up when you're working with your own project data.

In [ ]:
# Count missing values per column
df.isna().sum()

In [ ]:
# Drop rows where rating is missing — store as a new DataFrame
df_rated = df.dropna(subset=["rating"])
print(f"Original: {df.shape[0]} rows")
print(f"After dropping missing ratings: {df_rated.shape[0]} rows")

# Note: when you ran .mean() on rating in groupby,
# pandas silently ignored NaN values — useful, but worth knowing.

---
## Part 7 — Dictionaries and what a DataFrame actually is

Here's something worth knowing: **a DataFrame is essentially a dictionary of lists.**

The column names are dictionary keys. Each column's values are a list. That's the structure pandas builds when you load a CSV — and it's why `df["column_name"]` looks like a dictionary lookup. Because it is one.

In [ ]:
# A dictionary of lists
data = {
    "restaurant": ["Spice Garden", "Burger Barn", "Pizza Palace"],
    "rating": [4.5, 3.8, 4.2],
    "orders": [42, 31, 55]
}

# Create a DataFrame directly from a dictionary
mini_df = pd.DataFrame(data)
mini_df

In [ ]:
# Column names are dictionary keys
print(data.keys())

# Accessing a column from the DataFrame — same syntax as a dictionary
print(mini_df["rating"])

### Dictionary exercises

In [ ]:
# Exercise 1: create a dictionary with three QuickBite restaurants,
# their cuisine types, and average ratings.
# Print each key/value pair using a for loop over .items()

quickbite_info = {
    # your entries here
}

for key, value in quickbite_info.items():
    print(f"{key}: {value}")

In [ ]:
# Exercise 2: access a specific value by key from your dictionary

In [ ]:
# Exercise 3: add a new key/value pair to an existing dictionary
restaurant_ratings = {"Spice Garden": 4.5, "Burger Barn": 3.8, "Pizza Palace": 4.2}

# Add Sushi Spot with a rating of 4.7

**Stretch:** Create a small DataFrame from a dictionary of your own — at least 4 columns and 5 rows of QuickBite-themed data. Run `.describe()` on it.

In [ ]:
# Stretch

### Commentary cell 6

1. What is a dictionary? How is it different from a list?
2. How does understanding a DataFrame as "a dictionary of lists" change how you think about it — and why `df["column"]` works the way it does?
3. Where did anything you learned in weeks 1–3 (variables, loops, functions) help you in this week's exercises?

*Your commentary here*

---

## Done for today

```bash
git add . && git commit -m "week 4 session" && git push
```

**Homework:** `week04/homework_notebook.ipynb` — RideAlong data, same scope. Complete it before Week 5.

No Blackboard Journal action needed this week.